/* The following code was generated by JFlex 1.3.5 on 12/10/22, 11:31 PM */

package cup.example;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 12/10/22, 11:31 PM from the specification file
 * <tt>file:/C:/Users/alex_/eclipse-workspace/TranslatorDesignLab/TranslatorDesignLab/TDLab/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\22\1\0\1\14"+
    "\7\0\1\0\2\0\1\5\1\32\1\15\12\13\1\7\1\0\1\4"+
    "\1\31\1\6\1\16\1\0\1\37\1\40\1\33\1\11\1\24\1\12"+
    "\2\5\1\26\2\5\1\21\1\20\1\30\1\27\1\34\1\5\1\10"+
    "\1\25\1\35\1\41\1\23\1\5\1\17\1\36\5\5\1\5\1\5"+
    "\1\37\1\40\1\33\1\11\1\24\1\12\2\5\1\26\2\5\1\21"+
    "\1\20\1\30\1\27\1\34\1\5\1\10\1\25\1\35\1\41\1\23"+
    "\1\5\1\17\1\36\1\5\uff85\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    34,    68,   102,    68,   136,   170,   204,   238,   272, 
      306,    68,   340,   374,   170,   408,   442,   476,   272,   272, 
       68,   510,   544,   408,   578,   612,   646,   680,   442,   714, 
      748,   782,   816,   850,   884,   918,   952,   986,  1020,  1054, 
     1088,  1122,  1156,   408,   408,  1190,  1224,  1258,  1292,  1326, 
     1360,  1394,   408,  1428,  1462,  1496,  1530,  1564,  1598,  1632, 
     1666,  1700,  1734,  1768,   408,  1802,  1836,  1870,    68,  1904, 
     1938,  1972,  2006,   408,    68,  2040,  2074,  2108,  2142,  2176, 
     2210,    68,  2244,  2278,  2312,  2346,  2380,   408,  2414,  2448, 
     2482,  2516,  2550,  2584,  2618,  2652,  2686,   408,  2720,  2754, 
     2788,  2822,    68,  2856,  2890,  2924,    68
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\3\1\11"+
    "\3\7\1\12\1\13\1\3\3\7\1\5\6\7\1\14"+
    "\1\3\7\7\42\3\44\0\1\5\54\0\1\15\1\16"+
    "\30\0\1\17\1\0\1\20\4\17\3\0\3\17\1\0"+
    "\6\17\2\0\7\17\2\21\1\0\37\21\5\0\1\17"+
    "\1\0\1\20\1\17\1\22\2\17\3\0\3\17\1\0"+
    "\6\17\2\0\7\17\2\23\1\0\11\23\1\24\25\23"+
    "\6\0\1\25\43\0\1\26\50\0\1\27\27\0\1\30"+
    "\2\0\4\30\3\0\3\30\1\0\6\30\2\0\7\30"+
    "\2\21\1\0\1\21\1\31\35\21\5\0\1\17\1\0"+
    "\1\20\2\17\1\32\1\17\3\0\3\17\1\0\6\17"+
    "\2\0\7\17\11\0\1\33\50\0\1\34\21\0\2\21"+
    "\1\0\1\21\1\31\10\21\1\35\24\21\5\0\1\17"+
    "\1\0\1\36\4\17\3\0\3\17\1\0\6\17\2\0"+
    "\7\17\12\0\1\37\50\0\1\40\25\0\1\30\2\0"+
    "\1\41\1\42\2\30\3\0\2\30\1\43\1\0\3\30"+
    "\1\44\2\30\2\0\2\30\1\45\1\30\1\46\2\30"+
    "\7\0\1\47\54\0\1\50\24\0\1\30\2\0\1\30"+
    "\1\51\2\30\3\0\3\30\1\0\1\30\1\52\4\30"+
    "\2\0\7\30\5\0\1\30\2\0\4\30\3\0\3\30"+
    "\1\0\1\30\1\53\4\30\2\0\7\30\5\0\1\30"+
    "\2\0\4\30\3\0\3\30\1\0\3\30\1\54\2\30"+
    "\2\0\7\30\5\0\1\30\2\0\1\30\1\55\2\30"+
    "\3\0\3\30\1\0\6\30\2\0\7\30\5\0\1\30"+
    "\2\0\4\30\3\0\3\30\1\0\6\30\2\0\3\30"+
    "\1\56\3\30\5\0\1\30\2\0\4\30\3\0\3\30"+
    "\1\0\6\30\2\0\5\30\1\57\1\30\10\0\1\60"+
    "\1\61\7\0\1\62\13\0\1\63\27\0\1\64\23\0"+
    "\1\30\2\0\2\30\1\65\1\30\3\0\3\30\1\0"+
    "\6\30\2\0\7\30\5\0\1\30\2\0\4\30\3\0"+
    "\3\30\1\0\2\30\1\66\3\30\2\0\7\30\5\0"+
    "\1\30\2\0\4\30\3\0\3\30\1\0\2\30\1\67"+
    "\3\30\2\0\7\30\5\0\1\30\2\0\4\30\3\0"+
    "\3\30\1\0\6\30\2\0\1\30\1\70\5\30\5\0"+
    "\1\30\2\0\4\30\3\0\3\30\1\0\4\30\1\71"+
    "\1\30\2\0\7\30\11\0\1\72\54\0\1\73\43\0"+
    "\1\74\51\0\1\75\27\0\1\76\22\0\1\30\2\0"+
    "\4\30\3\0\3\30\1\0\4\30\1\77\1\30\2\0"+
    "\7\30\5\0\1\30\2\0\4\30\3\0\3\30\1\0"+
    "\6\30\2\0\1\100\6\30\5\0\1\30\2\0\4\30"+
    "\3\0\3\30\1\0\1\30\1\101\4\30\2\0\7\30"+
    "\5\0\1\30\2\0\4\30\3\0\3\30\1\0\6\30"+
    "\2\0\6\30\1\102\12\0\1\103\54\0\1\104\22\0"+
    "\1\105\67\0\1\106\15\0\1\107\36\0\1\30\2\0"+
    "\4\30\3\0\3\30\1\0\6\30\2\0\6\30\1\110"+
    "\5\0\1\30\2\0\1\111\3\30\3\0\3\30\1\0"+
    "\6\30\2\0\7\30\5\0\1\30\2\0\4\30\3\0"+
    "\3\30\1\0\6\30\2\0\2\30\1\112\4\30\6\0"+
    "\1\113\66\0\1\114\32\0\1\115\42\0\1\116\21\0"+
    "\1\30\2\0\1\117\3\30\3\0\3\30\1\0\6\30"+
    "\2\0\7\30\5\0\1\30\2\0\4\30\3\0\3\30"+
    "\1\0\3\30\1\120\2\30\2\0\7\30\10\0\1\121"+
    "\37\0\1\122\61\0\1\123\20\0\1\30\2\0\4\30"+
    "\3\0\3\30\1\0\6\30\2\0\1\124\6\30\5\0"+
    "\1\30\2\0\4\30\3\0\3\30\1\0\6\30\2\0"+
    "\1\30\1\125\5\30\26\0\1\126\42\0\1\127\17\0"+
    "\1\30\2\0\4\30\3\0\3\30\1\0\1\30\1\130"+
    "\4\30\2\0\7\30\5\0\1\30\2\0\4\30\3\0"+
    "\3\30\1\0\6\30\2\0\2\30\1\131\4\30\34\0"+
    "\1\132\35\0\1\133\16\0\1\30\2\0\4\30\3\0"+
    "\3\30\1\0\3\30\1\134\2\30\2\0\7\30\35\0"+
    "\1\135\35\0\1\136\15\0\1\30\2\0\4\30\3\0"+
    "\3\30\1\0\4\30\1\137\1\30\2\0\7\30\26\0"+
    "\1\140\27\0\1\141\32\0\1\30\2\0\4\30\3\0"+
    "\3\30\1\0\5\30\1\142\2\0\7\30\27\0\1\143"+
    "\25\0\1\144\56\0\1\145\43\0\1\146\15\0\1\147"+
    "\46\0\1\150\42\0\1\151\43\0\1\152\31\0\1\153"+
    "\33\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  9,  1,  1,  1,  1,  1,  1,  9,  1,  0,  0,  0, 
     0,  0,  0,  1,  9,  0,  0,  1,  1,  0,  0,  0,  1,  0,  0,  0, 
     1,  1,  1,  1,  1,  1,  0,  0,  1,  1,  1,  1,  1,  1,  1,  0, 
     0,  0,  0,  0,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  1,  1, 
     1,  1,  0,  0,  9,  0,  0,  1,  1,  1,  9,  0,  0,  0,  1,  1, 
     0,  9,  0,  1,  1,  0,  0,  1,  1,  0,  0,  1,  0,  0,  1,  0, 
     0,  1,  0,  0,  0,  0,  9,  0,  0,  0,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	

    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
	return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[2958];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 150) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 11: 
          {  return symbolFactory.newSymbol("EQUALS", EQUALS, yytext());  }
        case 108: break;
        case 73: 
          { return symbolFactory.newSymbol("RDF_ABOUT", RDF_ABOUT, yytext());  }
        case 109: break;
        case 81: 
          {  return symbolFactory.newSymbol("CLOSE_RDF_TYPE", CLOSE_RDF_TYPE, yytext());  }
        case 110: break;
        case 64: 
          {  return symbolFactory.newSymbol("OPEN_RDF_TYPE", OPEN_RDF_TYPE, yytext());  }
        case 111: break;
        case 23: 
        case 32: 
        case 33: 
        case 34: 
        case 35: 
        case 36: 
        case 37: 
        case 40: 
        case 41: 
        case 42: 
        case 45: 
        case 46: 
        case 53: 
        case 54: 
        case 55: 
        case 56: 
        case 62: 
        case 63: 
        case 65: 
        case 71: 
        case 72: 
        case 78: 
        case 79: 
        case 83: 
        case 84: 
        case 88: 
        case 91: 
        case 94: 
          {  return symbolFactory.newSymbol("TAG_NAME_WITH_SCHEME", TAG_NAME_WITH_SCHEME, yytext());  }
        case 112: break;
        case 102: 
          {  return symbolFactory.newSymbol("CLOSE_RDF_DESCRIPTION", CLOSE_RDF_DESCRIPTION, yytext());  }
        case 113: break;
        case 97: 
          {  return symbolFactory.newSymbol("OPEN_RDF_DESCRIPTION", OPEN_RDF_DESCRIPTION, yytext());  }
        case 114: break;
        case 24: 
        case 28: 
          {  return symbolFactory.newSymbol("INSIDE_TEXT", INSIDE_TEXT, yytext());  }
        case 115: break;
        case 68: 
          {  return symbolFactory.newSymbol("CLOSE_RDF_LI", CLOSE_RDF_LI, yytext());  }
        case 116: break;
        case 19: 
          {  return symbolFactory.newSymbol("PROPERTY_VALUE", PROPERTY_VALUE, yytext());  }
        case 117: break;
        case 5: 
          {  return symbolFactory.newSymbol("OPEN_TAG", OPEN_TAG, yytext());  }
        case 118: break;
        case 12: 
          {  return symbolFactory.newSymbol("OPEN_END_TAG", OPEN_END_TAG, yytext());  }
        case 119: break;
        case 52: 
          {  return symbolFactory.newSymbol("OPEN_RDF_RDF", OPEN_RDF_RDF, yytext());  }
        case 120: break;
        case 106: 
          {  return symbolFactory.newSymbol("XML_VERSION", XML_VERSION, yytext());  }
        case 121: break;
        case 44: 
          { return symbolFactory.newSymbol("RDF_ID", RDF_ID, yytext());  }
        case 122: break;
        case 20: 
          {  return symbolFactory.newSymbol("CLOSE_SINGULAR_TAG", CLOSE_SINGULAR_TAG, yytext());  }
        case 123: break;
        case 87: 
          { return symbolFactory.newSymbol("RDF_RESOURCE", RDF_RESOURCE, yytext());  }
        case 124: break;
        case 43: 
          {  return symbolFactory.newSymbol("OPEN_RDF_LI", OPEN_RDF_LI, yytext());  }
        case 125: break;
        case 74: 
          {  return symbolFactory.newSymbol("CLOSE_RDF_RDF", CLOSE_RDF_RDF, yytext());  }
        case 126: break;
        case 2: 
        case 6: 
        case 8: 
        case 9: 
        case 10: 
          {  emit_warning("Unrecognized character '" +yytext()+"' -- ignored");  }
        case 127: break;
        case 7: 
          {  return symbolFactory.newSymbol("CLOSE_TAG", CLOSE_TAG, yytext());  }
        case 128: break;
        case 3: 
        case 4: 
          {  }
        case 129: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
