
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CLOSE_RDF_DESCRIPTION = 17;
  public static final int OPEN_RDF_DESCRIPTION = 13;
  public static final int RDF_TYPE = 10;
  public static final int CLOSE_SINGULAR_TAG = 16;
  public static final int OPEN_END_TAG = 15;
  public static final int RDF_LI = 8;
  public static final int OPEN_RDF_TYPE = 14;
  public static final int RDF_DESCRIPTION = 9;
  public static final int RDF_ID = 11;
  public static final int CLOSE_RDF_RDF = 5;
  public static final int CLOSE_TAG = 6;
  public static final int EQUALS = 19;
  public static final int EOF = 0;
  public static final int RDF_RESOURCE = 7;
  public static final int error = 1;
  public static final int PROPERTY_VALUE = 23;
  public static final int OPEN_RDF_RDF = 4;
  public static final int RDF_ABOUT = 12;
  public static final int CLOSE_RDF_LI = 22;
  public static final int OPEN_RDF_LI = 20;
  public static final int TAG_NAME_WITH_SCHEME = 18;
  public static final int OPEN_TAG = 3;
  public static final int XML_VERSION = 2;
  public static final int INSIDE_TEXT = 24;
  public static final int CLOSE_RDF_TYPE = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "XML_VERSION",
  "OPEN_TAG",
  "OPEN_RDF_RDF",
  "CLOSE_RDF_RDF",
  "CLOSE_TAG",
  "RDF_RESOURCE",
  "RDF_LI",
  "RDF_DESCRIPTION",
  "RDF_TYPE",
  "RDF_ID",
  "RDF_ABOUT",
  "OPEN_RDF_DESCRIPTION",
  "OPEN_RDF_TYPE",
  "OPEN_END_TAG",
  "CLOSE_SINGULAR_TAG",
  "CLOSE_RDF_DESCRIPTION",
  "TAG_NAME_WITH_SCHEME",
  "EQUALS",
  "OPEN_RDF_LI",
  "CLOSE_RDF_TYPE",
  "CLOSE_RDF_LI",
  "PROPERTY_VALUE",
  "INSIDE_TEXT"
  };
}

